# Generated by Django 6.0.5 on 2026-05-28 11:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=3, unique=True)),
                ('number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='drivers/')),
                ('country', models.CharField(blank=True, max_length=50)),
                ('country_code', models.CharField(blank=True, help_text='ISO 3166-1 alpha-3', max_length=3)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_reserve', models.BooleanField(default=False)),
                ('fastf1_driver_id', models.CharField(blank=True, help_text='FastF1 driver identifier', max_length=50)),
                ('headshot_url', models.URLField(blank=True, help_text='URL from FastF1 for driver headshot')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_name', models.CharField(max_length=30)),
                ('color_primary', models.CharField(default='#FFFFFF', help_text='Hex color e.g. #E8002D', max_length=7)),
                ('color_secondary', models.CharField(default='#000000', max_length=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/')),
                ('constructor_id', models.CharField(blank=True, help_text='FastF1 team identifier', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(default=2026)),
                ('round_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('name', models.CharField(max_length=200)),
                ('official_name', models.CharField(blank=True, max_length=300)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('circuit_name', models.CharField(blank=True, max_length=200)),
                ('fp1_date', models.DateTimeField(blank=True, null=True)),
                ('fp2_date', models.DateTimeField(blank=True, null=True)),
                ('fp3_date', models.DateTimeField(blank=True, null=True)),
                ('qualifying_date', models.DateTimeField(blank=True, null=True)),
                ('sprint_qualifying_date', models.DateTimeField(blank=True, null=True)),
                ('sprint_date', models.DateTimeField(blank=True, null=True)),
                ('race_date', models.DateTimeField()),
                ('has_sprint', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('fastf1_event_name', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['season', 'round_number'],
                'unique_together': {('season', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('qualifying', 'Qualifying'), ('sprint', 'Sprint'), ('race', 'Race')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('p1_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicted_p1', to='core.driver', verbose_name='Predicted P1')),
                ('p2_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicted_p2', to='core.driver', verbose_name='Predicted P2')),
                ('p3_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicted_p3', to='core.driver', verbose_name='Predicted P3')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='core.race')),
            ],
            options={
                'ordering': ['-race__round_number'],
            },
        ),
        migrations.CreateModel(
            name='SessionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('qualifying', 'Qualifying'), ('sprint', 'Sprint'), ('race', 'Race')], max_length=20)),
                ('position', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('grid_position', models.IntegerField(blank=True, null=True)),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(default='Finished', max_length=50)),
                ('fastest_lap', models.BooleanField(default=False)),
                ('gap_to_leader', models.CharField(blank=True, max_length=50)),
                ('laps_completed', models.IntegerField(default=0)),
                ('time', models.CharField(blank=True, help_text='Finishing time or qualifying time', max_length=50)),
                ('q1_time', models.CharField(blank=True, max_length=20)),
                ('q2_time', models.CharField(blank=True, max_length=20)),
                ('q3_time', models.CharField(blank=True, max_length=20)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.race')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='StandingsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(default=2026)),
                ('round_number', models.IntegerField()),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('position', models.IntegerField()),
                ('snapshot_type', models.CharField(choices=[('driver', 'Driver'), ('constructor', 'Constructor')], max_length=15)),
                ('wins', models.IntegerField(default=0)),
                ('podiums', models.IntegerField(default=0)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='core.driver')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='core.team')),
            ],
            options={
                'ordering': ['season', 'round_number', 'position'],
            },
        ),
        migrations.CreateModel(
            name='DriverTeamHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(default=2026)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField(blank=True, help_text='Null means currently active', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_history', to='core.driver')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_history', to='core.team')),
            ],
            options={
                'verbose_name': 'Driver Team Assignment',
                'verbose_name_plural': 'Driver Team Assignments',
                'ordering': ['-season', '-date_from'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('favorite_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
        migrations.CreateModel(
            name='PredictionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('qualifying', 'Qualifying'), ('sprint', 'Sprint'), ('race', 'Race')], max_length=20)),
                ('exact_p1', models.BooleanField(default=False)),
                ('exact_p2', models.BooleanField(default=False)),
                ('exact_p3', models.BooleanField(default=False)),
                ('correct_drivers', models.IntegerField(default=0, help_text='Drivers in top 3 but wrong position')),
                ('exact_podium_bonus', models.BooleanField(default=False, help_text='All 3 positions exact')),
                ('total_points', models.IntegerField(default=0)),
                ('scored_at', models.DateTimeField(auto_now_add=True)),
                ('actual_p1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.driver')),
                ('actual_p2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.driver')),
                ('actual_p3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.driver')),
                ('prediction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='core.prediction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_scores', to=settings.AUTH_USER_MODEL)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_scores', to='core.race')),
            ],
            options={
                'ordering': ['-total_points'],
                'indexes': [models.Index(fields=['user', 'total_points'], name='core_predic_user_id_4b5645_idx'), models.Index(fields=['race', 'session_type'], name='core_predic_race_id_b73fdd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['user', 'race'], name='core_predic_user_id_84a21e_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['race', 'session_type'], name='core_predic_race_id_3287a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='prediction',
            unique_together={('user', 'race', 'session_type')},
        ),
        migrations.AddIndex(
            model_name='sessionresult',
            index=models.Index(fields=['race', 'session_type', 'position'], name='core_sessio_race_id_803fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionresult',
            index=models.Index(fields=['driver', 'session_type'], name='core_sessio_driver__3c2ed3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionresult',
            unique_together={('race', 'driver', 'session_type')},
        ),
        migrations.AddIndex(
            model_name='standingssnapshot',
            index=models.Index(fields=['season', 'round_number', 'snapshot_type'], name='core_standi_season_87b4b5_idx'),
        ),
        migrations.AddIndex(
            model_name='standingssnapshot',
            index=models.Index(fields=['driver', 'season'], name='core_standi_driver__b3c6f4_idx'),
        ),
        migrations.AddIndex(
            model_name='standingssnapshot',
            index=models.Index(fields=['team', 'season'], name='core_standi_team_id_0872f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='driverteamhistory',
            constraint=models.UniqueConstraint(fields=('driver', 'team', 'season', 'date_from'), name='unique_driver_team_season_date'),
        ),
    ]
